### ISSUE TITLE
Understanding Models 

### ISSUE THREAD

**Issue by Zakintosh** [springleng/dysaas#1]
Hello i appreciate the work you just did, i just have a simple question about the Models.

You refer to what with User, Member i can't understand what represent for you each Model of this two.

i'm facing a situation when i have to be able to manage subscriptions.

can you please describe more i will be thankful.

**Comment by springleng** [comment]
> Hello i appreciate the work you just did, i just have a simple question about the Models.
> 
> You refer to what with User, Member i can't understand what represent for you each Model of this two.
> 
> i'm facing a situation when i have to be able to manage subscriptions.
> 
> can you please describe more i will be thankful.

User equals tenants and members belong to tenants.
